// AUTOGENERATED - DO NOT MODIFY

// View component imports — one per viewport declared in ui_extension.views
import App from '../src/views/App';
import CustomerDetailView from '../src/views/CustomerDetailView';

// Exposes the SDK version so the Dashboard can verify compatibility
export * from '@stripe/ui-extension-sdk/version';

// Named exports make each view component accessible to the Dashboard runtime

export { 
  App,

  CustomerDetailView
 };

// Timestamp changes on every export, ensuring the dev server detects a rebuild
export const BUILD_TIME = '2026-07-30 21:08:41.2714796 +0100 WAT m=+5248.106086501';

// App manifest — consumed by the Dashboard to configure the app
export default {
  "$schema": "https://stripe.com/stripe-app.schema.json",
  "constants": {
    "API_BASE": "https://churnguardapp.com/api/stripe-app"
  },
  "distribution_type": "public",
  "icon": "./public/icon.png",
  "id": "com.churnguard.risk-monitor",
  "name": "ChurnGuard",
  "permissions": [
    {
      "permission": "customer_read",
      "purpose": "Identify customers at risk of churning based on their profile and payment history"
    },
    {
      "permission": "subscription_read",
      "purpose": "Detect past-due, cancelling, and at-risk subscriptions"
    },
    {
      "permission": "charge_read",
      "purpose": "Calculate churn risk from failed and missing payment attempts"
    }
  ],
  "post_install_action": {
    "type": "external",
    "url": "https://churnguardapp.com/stripe-app/install"
  },
  "ui_extension": {
    "content_security_policy": {
      "connect-src": [
        "https://churnguardapp.com/api/"
      ],
      "purpose": "ChurnGuard backend API for AI-powered churn risk scores and retention data"
    },
    "views": [
      {
        "component": "App",
        "viewport": "stripe.dashboard.home.overview"
      },
      {
        "component": "CustomerDetailView",
        "viewport": "stripe.dashboard.customer.detail"
      }
    ]
  },
  "version": "0.0.6"
};
